baseURL = "https://plasticrice8-cpu.github.io/photorepo/"
languageCode = "en-us"
title = "Oliver Yee"
theme = "hugo-theme-gallery"

[params]
  description = "Photography"
  imageCount = true
  thumbWidth = 1200
  sortBy = "Name"
  sortOrder = "asc"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
